-- Ensure the default buy-three-get-one offer exists for current and new stores.
INSERT INTO `Promotion` (
    `id`,
    `code`,
    `name`,
    `description`,
    `type`,
    `value`,
    `startAt`,
    `endAt`,
    `minOrderValue`,
    `totalUsageLimit`,
    `usagePerCustomer`,
    `buyQuantity`,
    `getQuantity`,
    `memberOnly`,
    `isActive`,
    `createdAt`,
    `updatedAt`
) VALUES (
    'promo-mua3tang1',
    'MUA3TANG1',
    'Mua 3 tặng 1',
    'Chọn 4 món kem bất kỳ, món có giá thấp nhất được miễn phí',
    'BUY_X_GET_Y',
    0,
    '2025-01-01 00:00:00.000',
    '2099-12-31 23:59:59.999',
    0,
    5000,
    50,
    3,
    1,
    false,
    true,
    CURRENT_TIMESTAMP(3),
    CURRENT_TIMESTAMP(3)
)
ON DUPLICATE KEY UPDATE
    `name` = VALUES(`name`),
    `description` = VALUES(`description`),
    `type` = VALUES(`type`),
    `value` = VALUES(`value`),
    `startAt` = VALUES(`startAt`),
    `endAt` = VALUES(`endAt`),
    `minOrderValue` = VALUES(`minOrderValue`),
    `totalUsageLimit` = VALUES(`totalUsageLimit`),
    `usagePerCustomer` = VALUES(`usagePerCustomer`),
    `buyQuantity` = VALUES(`buyQuantity`),
    `getQuantity` = VALUES(`getQuantity`),
    `memberOnly` = VALUES(`memberOnly`),
    `isActive` = VALUES(`isActive`),
    `updatedAt` = CURRENT_TIMESTAMP(3);
